itemconfig:
  password: ENC(wXLeqHTYfDCRoDfaFh1GZVUh7KnklErv)
  ipassword: ENC(oiEPnHGYcZCENpFjOUDljw==)


jasypt:
  encryptor:
    bean: encryptorBean
    password: ${JASYPT_ENCRYPTOR_PASSWORD:12345}